version: "2.2"
services:

  backend:
    build:
      context: .
    ports:
      - "4000:4000"
    volumes:
      - .:/code
    env_file:
      - .env

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - ./data/redis:/data
    depends_on:
      - backend
    ports:
    - ${REDIS_PORT}:${REDIS_PORT}

  worker:
    build: .
    command: celery -A app.worker.celery_app worker -l DEBUG
    volumes:
      - .:/code
    depends_on:
      - backend
      - redis