version: "2.2"
services:
  nginx:
    image: nginx
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    ports:
    - 80:80

  backend:
    build:
      context: .
    ports:
      - "4000:4000"
    volumes:
      - .:/code
    env_file:
      - .env

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - ./data/redis:/data
    depends_on:
      - backend
    ports:
    - ${REDIS_PORT}:${REDIS_PORT}

  worker:
    build: .
    command: celery -A app.worker.celery_app worker -l DEBUG
    volumes:
      - .:/code
    depends_on:
      - backend
      - redis